"""Report rendering helpers."""

from datetime import UTC, datetime
from typing import Any


def utc_now_iso() -> str:
    return datetime.now(UTC).isoformat()


def evidence_line(metric: str, pod: str, endpoint: str, source: str) -> str:
    return f"Evidence: metric:{metric}; pod:{pod}; endpoint:{endpoint}; source:{source}"


def build_deterministic_markdown(
    metrics: dict[str, Any],
    consistency_checks: dict[str, Any],
    timeline: list[dict[str, Any]],
) -> str:
    top = metrics["top_depended_pods"][:3]
    impacts = metrics["failure_impact"][:3]
    spofs = metrics["hidden_spofs"][:3]

    lines: list[str] = []
    lines.append("### Deterministic Findings")
    lines.append("")
    lines.append("#### Most Depended-Upon Pods")
    for item in top:
        lines.append(
            f"- `{item['pod_id']}` has in-degree `{item['in_degree']}` and weighted in-degree `{item['weighted_in_degree']}`."
        )
        lines.append(
            evidence_line(
                "weighted_in_degree",
                item["pod_id"],
                "/dependencies",
                "dependency_graph",
            )
        )
    lines.append("")
    lines.append("#### Failure Impact")
    for impact in impacts:
        lines.append(
            f"- If `{impact['pod_id']}` fails: immediate dependents `{impact['immediate_count']}`, transitive impact `{impact['transitive_count']}`."
        )
        lines.append(
            evidence_line(
                "failure_impact_transitive_count",
                impact["pod_id"],
                "/dependencies",
                "dependency_graph",
            )
        )
    lines.append("")
    lines.append("#### Hidden Single Points of Failure")
    if spofs:
        for spof in spofs:
            lines.append(
                f"- `{spof['pod_id']}` behaves as a potential SPOF with transitive impact `{spof['transitive_count']}`."
            )
            lines.append(
                evidence_line(
                    "hidden_spof_transitive_threshold",
                    spof["pod_id"],
                    "/dependencies",
                    "risk_metrics",
                )
            )
    else:
        lines.append("- No strong SPOF threshold exceeded in deterministic checks.")
        lines.append(
            evidence_line(
                "hidden_spof_transitive_threshold", "none", "n/a", "risk_metrics"
            )
        )
    lines.append("")
    lines.append("#### Supply vs Dependency Consistency")
    summary = consistency_checks["summary"]
    lines.append(
        f"- Missing reciprocal supply links: `{summary['missing_supply_link_count']}`; undocumented dependency links: `{summary['undocumented_dependency_link_count']}`; resource mismatches: `{summary['resource_mismatch_count']}`."
    )
    lines.append(
        evidence_line("consistency_summary", "multi", "n/a", "consistency_checks")
    )
    lines.append("")
    lines.append("#### Infrastructure Evolution (Logs + Comms)")
    if timeline:
        sample = timeline[:2] + timeline[-2:]
        for event in sample:
            lines.append(
                f"- `{event['timestamp']}` `{event['pod_id']}` `{event['event']}`: {event['detail']}"
            )
            lines.append(
                evidence_line(
                    "timeline_event",
                    event["pod_id"],
                    event["endpoint"] or "n/a",
                    "timeline",
                )
            )
    else:
        lines.append("- Insufficient data to build timeline events.")
        lines.append(evidence_line("timeline_event_count", "none", "n/a", "timeline"))
    return "\n".join(lines)


def assemble_report(args: dict[str, Any]) -> str:
    consistency_checks = args["consistency_checks"]
    return (
        "# Project Selene Infrastructure Report\n\n"
        "## Executive Summary\n"
        "- Report generated from deterministic graph and consistency analysis.\n"
        f"- Discovered pods: `{args['discovered_pod_count']}`.\n"
        f"- Dependency edges: `{args['dependency_edge_count']}`; supply edges: `{args['supply_edge_count']}`.\n"
        f"- LLM synthesis model: `{args['llm_model']}`.\n\n"
        "## Dependency Graph (Mermaid)\n"
        "```mermaid\n"
        f"{args['mermaid_graph']}\n"
        "```\n\n"
        "## Dependency Graph (Text View)\n"
        f"{args['text_graph']}\n\n"
        "## Deterministic Risk and Consistency Analysis\n"
        f"{args['deterministic_markdown']}\n\n"
        "## LLM Synthesis (Grounded)\n"
        "_Narrative only. Evidence citations are deterministic and generated by code._\n\n"
        f"{args['llm_text']}\n\n"
        "## Data Completeness and Verification\n"
        f"- Endpoint coverage gaps: `{consistency_checks['summary']['endpoint_coverage_gap_count']}`.\n"
        f"- Unknown pod references: `{consistency_checks['summary']['unknown_pod_reference_count']}`.\n"
        "- Findings without deterministic evidence are treated as insufficient data.\n"
    )


__all__ = [
    "assemble_report",
    "build_deterministic_markdown",
    "evidence_line",
    "utc_now_iso",
]
